### ISSUE TITLE
AlloyBlastSmelter can't be parallelized

### ISSUE THREAD

**Issue by Sanduhr32** [GregTechCEu/gregicality-multiblocks#27] opened 2023-01-01 17:00 UTC
AlloyBlastSmelter should probably extend GCYMRecipeMapMultiblockController instead of RecipeMapMultiblockController
like the LargeArcFurnace

https://github.com/GregTechCEu/gregicality-multiblocks/blob/0d8177a1ed23af65b7c79f5ba3ba8a9455f2109d/src/main/java/gregicality/multiblocks/common/metatileentities/multiblock/standard/MetaTileEntityLargeArcFurnace.java#L22

https://github.com/GregTechCEu/gregicality-multiblocks/blob/0d8177a1ed23af65b7c79f5ba3ba8a9455f2109d/src/main/java/gregicality/multiblocks/common/metatileentities/multiblock/standard/MetaTileEntityAlloyBlastSmelter.java#L49

**Comment by TechLord22** [comment] 2023-01-01 17:16
The Alloy Blast Smelter is intentionally non-parallelizable. It is meant to be an alternative to the regular Blast Furnace for alloys. It has a significant speed boost over it for base recipe durations, in addition to the added bonus of skipping the mixer step. It also has coil overclocking, which allows for huge bulk production as you upgrade the multiblock. It shouldn't need parallelization, given how fast it is already.

Additionally, combining coil overclocking with parallel recipes is incredibly overpowered, and this behavior is reserved for the Rotary Hearth Furnace.

For the above reasons, parallelization in the Alloy Blast Smelter does not make sense for GCYM, and is also not a bug. Therefore, I'm closing this issue.

**Closed by TechLord22** 2023-01-01 17:16 UTC
Labels: wontfix

**Comment by Sanduhr32** [comment] 2023-01-03 21:16
i never marked this as a bug ;(
i understand that you don't want to outclass the rotary hearth furnace,

however mixing isn't that slow and you have to solidify/cool the molten alloys making that point irrelevant.
thanks for explaining.
A wiki or something where such intentional decisions are documented would be great.

**Comment by Sanduhr32** [comment] 2023-01-03 23:59
I've thought about this more and came to a conclusion, what about a config for parallelizing the ABF, which is false by default?
Reasoning behind this is [Nomifactory](https://www.curseforge.com/minecraft/modpacks/nomi-ceu) only allowing to craft for example Watertight Steel only through the ABF via its molten variant.
(hot ingot requires dust, which requires ingot, which requires hot ingot or molten)

**Comment by ghzdude** [comment] 2023-01-04 00:02
The main purpose of the Alloy Blast Smelter is to craft the alloys for GCYM. You can use the Rotary Hearth Furnace instead (along with the Mega Blast Chiller), which _does_ accept parallelization hatches.
